### PR TITLE
Extend login #254

### LINKED ISSUE #254: Extend session login time

### PR DESCRIPTION
**Pull request by LEVI-RIVKIN**
This PR **should** be squashed.

Closes #254

### CODE REVIEW

**Comment by yitshak** [comment]
Levi, I started looking at the code.  Could you please provide a summary of what the issue and was it fixed?

**Comment by iddanh** [comment]
Why are so many files changed? Are you sure it is aligned with `main`?

**Comment by LEVI-RIVKIN** [comment]
> Why are so many files changed? Are you sure it is aligned with `main`?

@iddanh I am sure it is aligned with main.
The reason for the relatively many changes is that the login with `firebase/auth` was moved entirely to the client (as intended).
The backend will only deal with `firebase-admin/auth` from now on.

I've also discussed this with @maorohana-redis and he agreed.

BTW @maorohana-redis can you review?

**Comment by LEVI-RIVKIN** [comment]
> Levi, I started looking at the code. Could you please provide a summary of what the issue and was it fixed?

@yitshak

Summary:
The reason for the short session time in the past was due to a wrong use of the package `firebase/auth` in our backend.
One of the things this package can do is to login and maintain a session for a logged in user in the client. The package is doing it using what they call a `refreshToken` and an `idToken`. The `refreshToken` is a long lived one with which the client can obtain the short lived `idToken` to verify the user on the backend.
Before this PR we have wrongly used the `firebase/auth` package in our backend to login the user and the backend returned the short lived `idToken` to the client. Then the client had no control and no way to obtain a new `idToken` to keep the user in session.

This PR, in general, changes this and moves the use of `firebase/auth` entirely to the client, as intended.
There are also some minor changes of some lint suggestions and some restructuring of client services in light of these changes.

**Comment by LEVI-RIVKIN** [comment]
@yitshak @iddanh What is the holdup here? Was it not tested yet?

@maorohana-redis Will you have a chance to review?

**Review by yitshak — APPROVED** [review]
LGTM

**Comment by yitshak** [comment]
already merged in alternative PR

**Pull request closed without merging**
