### PR TITLE
add route guards and 401 handling (fix Ezer-Lachaim#277)

### PR DESCRIPTION
**Pull request by LEVI-RIVKIN**
This PR is quite large and is touching the infrastructure of the client project.

Changes:
1. Added `AuthRoute` guard which handles redirects for the different states of a user.
2. `Passenger` and `Driver` route redirects are now handled in their respective main component and is fired on change of `activeRide` instead of only on startup.
3. Added `Routes.tsx` under `Client` sub project similar to as it is in `Backoffice`.
4. Rewrite of the `Config.tsx` file/service into two different services - `auth` and `api`.
5. Rewrite of the `UserContext.tsx` context so that the `user` part becomes a part of the `auth` service and the `activeRide` part becomes a react hook.
6. Added a middleware to catch any 401 status on the api and reset the token and user.

#277

### CODE REVIEW

**Review by iddanh — COMMENTED** [review]
This is a huge PR, changes look good to me but we must test it on a STG env. 
@sharonamr @maorohana-redis any ETA on when it will be ready?

**Comment by LEVI-RIVKIN** [comment]
@iddanh @maorohana-redis Now that we have staging, can one of you merge this?

**Comment by iddanh** [comment]
I will deploy this to stg now, then we will ask Orlee and the testers to test all the flows, and then we can merge it and deploy to prod 💪

**Comment by iddanh** [comment]
This is deployed to staging and is ready for testing.
@OrleeTal It would be very helpful if you could help us test this, along with Alon and Shaindy.
Notice though that this branch is relative to the `master` branch, meaning it is without all the changes we did for the war.

**Comment by OrleeTal** [comment]
I understand, that's what I mentioned in one of my tickets; we should
release the war branch, not this old one which is missing many features.
Thanks

**Comment by LEVI-RIVKIN** [comment]
@OrleeTal This will eventually be released with the war branch.
At this point we want to make sure everything is working as expected for the non war branch on the staging environment. Once it is tested, we will merge it into the war branch and test it again on it.

**Comment by OrleeTal** [comment]
Understood.

**Comment by yitshak** [comment]
@iddanh I understand this is under testing now, right?

**Comment by iddanh** [comment]
Yes, it is on staging environment now waiting for testing

**Comment by LEVI-RIVKIN** [comment]
@iddanh @yitshak @OrleeTal 
Do we know what is the status with testing?

**Comment by iddanh** [comment]
I tested this on staging, and hope others did as well.
Looks good, merging this

**Pull request merged**
