### PR TITLE
Merge 'open-to-all' feature into main and activate it using an env variable

### PR DESCRIPTION
**Pull request by LEVI-RIVKIN**
The env variable `ALLOW_GUEST_RIDE_MODE=true` will activate the war mode.

This PR should **not** be squash merged so we don't loose all the history.

### CODE REVIEW

**Comment by iddanh** [comment]
@LEVI-RIVKIN please update this branch following the merge of #285 
Then we can deploy this to staging

**Comment by LEVI-RIVKIN** [comment]
@iddanh Done

**Comment by iddanh** [comment]
Deployed to staging, and set the flag. Looks good!

**Review by yitshak — APPROVED** [review]
LGTM

**Pull request merged**
